SELECT DISTINCT d.Customer , a.CUSPRODREF , a.ORDERNUMBER , a.Sectiondesc,
a.LOADDATE , a.DUEDATE ,
h.ProdCode , g.Description ,
g.RqdQty  AS QtyRequired
FROM FCADD a
INNER JOIN FCASOHE b ON a.SOHEKEY = b.SOHEKEY
LEFT OUTER JOIN FCSCP c ON a.STPAKEY = c.STPAKEY
INNER JOIN FSOSM d ON a.SosmKey = d.SosmKey
INNER JOIN FCASOSR g ON a.SoheKey = g.SoheKey
INNER JOIN FSTPA h ON g.StpaKey = h.StpaKey
INNER JOIN FSTPA e ON a.StpaKey = e.StpaKey
INNER JOIN FCACP f ON e.CacpKey = f.CacpKey
INNER JOIN FCACW i ON f.CacpKey = i.CacpKey
INNER JOIN FSTWC j ON i.StwcKey = j.StwcKey
WHERE b.MANUFACTPROCESS='A' AND g.Complete = 'N'
ORDER BY a.LOADDATE, a.CUSTOMER, a.CUSPRODREF, a.ORDERNUMBER, h.ProdCode
