"""
Security utilities.

Centralising token generation, sanitisation, and OWASP helpers here
means any blueprint can use them without duplicating code.
"""

import re
import secrets
import hashlib
from datetime import datetime, timedelta, timezone
from typing import Optional

import html
import re as _re_html

from itsdangerous import URLSafeTimedSerializer, BadSignature, SignatureExpired
from flask import current_app


# --- Token Helpers ---

def generate_token(data: str, salt: str = "default") -> str:
    """
    Generate a signed, time-stamped URL-safe token.

    Used for email verification and password reset links.
    The token encodes `data` (typically an email address) and expires
    based on ``max_age`` in :func:`verify_token`.
    """
    s = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])
    return s.dumps(data, salt=salt)


def verify_token(token: str, salt: str = "default", max_age: int = 3600) -> Optional[str]:
    """
    Verify and decode a token generated by :func:`generate_token`.

    Args:
        token:   The token string from the URL.
        salt:    Must match the salt used when generating.
        max_age: Token lifetime in seconds (default 1 hour).

    Returns:
        The original data string, or ``None`` if invalid/expired.
    """
    s = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])
    try:
        return s.loads(token, salt=salt, max_age=max_age)
    except (BadSignature, SignatureExpired):
        return None


def generate_secure_password(length: int = 16) -> str:
    """Generate a cryptographically secure random password."""
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()"
    return "".join(secrets.choice(alphabet) for _ in range(length))


# --- Input Sanitisation ---
# Uses stdlib `html` — no third-party dependency needed.
# Jinja2 auto-escapes all template output, so sanitisation here is a
# defence-in-depth measure for values stored in or returned from the DB.

_TAG_RE = _re_html.compile(r"<[^>]+>")


def sanitise_html(value: str) -> str:
    """
    Strip all HTML tags while preserving the text content (XSS prevention).

    Note: for richer allow-list sanitisation install `nh3` (the modern
    replacement for the deprecated `bleach`) and swap this implementation.
    """
    return _TAG_RE.sub("", value)


def sanitise_plain(value: str) -> str:
    """Escape ALL HTML special characters — safe for plain-text storage."""
    return html.escape(value, quote=True)


# --- Password Strength ---

def check_password_strength(password: str) -> tuple[bool, list[str]]:
    """
    Validate password against minimum security requirements.

    Returns:
        (is_valid, list_of_failure_messages)
    """
    errors: list[str] = []
    if len(password) < 10:
        errors.append("Password must be at least 10 characters long.")
    if not re.search(r"[A-Z]", password):
        errors.append("Password must contain at least one uppercase letter.")
    if not re.search(r"[a-z]", password):
        errors.append("Password must contain at least one lowercase letter.")
    if not re.search(r"\d", password):
        errors.append("Password must contain at least one digit.")
    if not re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        errors.append("Password must contain at least one special character.")
    return (len(errors) == 0, errors)


# --- Rate Limiting Helper (simple in-memory; use Redis in production) ---

_login_attempts: dict[str, list[datetime]] = {}
_MAX_ATTEMPTS = 5
_LOCKOUT_MINUTES = 15


def record_failed_login(identifier: str) -> None:
    """Record a failed login attempt for `identifier` (e.g. IP address or email)."""
    now = datetime.now(timezone.utc)
    attempts = _login_attempts.setdefault(identifier, [])
    # Prune attempts older than the lockout window
    _login_attempts[identifier] = [
        t for t in attempts if now - t < timedelta(minutes=_LOCKOUT_MINUTES)
    ]
    _login_attempts[identifier].append(now)


def is_locked_out(identifier: str) -> bool:
    """Return True if `identifier` has exceeded the allowed login attempts."""
    now = datetime.now(timezone.utc)
    attempts = _login_attempts.get(identifier, [])
    recent = [t for t in attempts if now - t < timedelta(minutes=_LOCKOUT_MINUTES)]
    return len(recent) >= _MAX_ATTEMPTS


def clear_login_attempts(identifier: str) -> None:
    """Clear failed attempts after a successful login."""
    _login_attempts.pop(identifier, None)
