"""add_product_context_fields_to_sales_order_lines

Revision ID: 0b24a2023d7a
Revises: 52e643958385
Create Date: 2026-04-30 09:27:57.540958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b24a2023d7a'
down_revision = '52e643958385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smv_matrix', schema=None) as batch_op:
        batch_op.drop_index('ix_smv_matrix_component_id')
        batch_op.drop_index('ix_smv_matrix_department_id')

    op.drop_table('smv_matrix')
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('product_group', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customer_group', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.drop_index('ix_sales_order_lines_customer_hold')
        batch_op.drop_index('ix_sales_order_lines_despatch_completed_date')
        batch_op.drop_index('ix_sales_order_lines_ops_missing')
        batch_op.drop_index('ix_sales_order_lines_order_completed_date')
        batch_op.drop_index('ix_sales_order_lines_planned_date')
        batch_op.drop_index('ix_sales_order_lines_production_ready_date')
        batch_op.create_index(batch_op.f('ix_sales_order_lines_customer_group'), ['customer_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_product_group'), ['product_group'], unique=False)
        batch_op.drop_column('despatch_completed_date')
        batch_op.drop_column('planned_date')
        batch_op.drop_column('customer_hold')
        batch_op.drop_column('ops_missing_since')
        batch_op.drop_column('customer_hold_note')
        batch_op.drop_column('production_ready_date')
        batch_op.drop_column('customer_hold_since')
        batch_op.drop_column('order_completed_date')
        batch_op.drop_column('ops_missing')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ops_missing', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('order_completed_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('customer_hold_since', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('production_ready_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('customer_hold_note', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ops_missing_since', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('customer_hold', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('planned_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('despatch_completed_date', sa.DATE(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_product_group'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_model'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_customer_group'))
        batch_op.create_index('ix_sales_order_lines_production_ready_date', ['production_ready_date'], unique=False)
        batch_op.create_index('ix_sales_order_lines_planned_date', ['planned_date'], unique=False)
        batch_op.create_index('ix_sales_order_lines_order_completed_date', ['order_completed_date'], unique=False)
        batch_op.create_index('ix_sales_order_lines_ops_missing', ['ops_missing'], unique=False)
        batch_op.create_index('ix_sales_order_lines_despatch_completed_date', ['despatch_completed_date'], unique=False)
        batch_op.create_index('ix_sales_order_lines_customer_hold', ['customer_hold'], unique=False)
        batch_op.drop_column('country')
        batch_op.drop_column('channel')
        batch_op.drop_column('customer_group')
        batch_op.drop_column('product_group')
        batch_op.drop_column('product_size')
        batch_op.drop_column('model')

    op.create_table('smv_matrix',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('timing_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('smv_minutes', sa.NUMERIC(precision=8, scale=3), nullable=True),
    sa.Column('ops', sa.INTEGER(), nullable=True),
    sa.Column('date_updated', sa.DATE(), nullable=True),
    sa.Column('confidence', sa.VARCHAR(length=20), nullable=False),
    sa.Column('last_modified_at', sa.DATETIME(), nullable=True),
    sa.Column('last_modified_by_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'department_id', name='uq_smv_comp_dept')
    )
    with op.batch_alter_table('smv_matrix', schema=None) as batch_op:
        batch_op.create_index('ix_smv_matrix_department_id', ['department_id'], unique=False)
        batch_op.create_index('ix_smv_matrix_component_id', ['component_id'], unique=False)

    # ### end Alembic commands ###
