"""add flow_order to departments

Revision ID: 128755418d31
Revises: df4b56349cc1
Create Date: 2026-03-11 14:03:04.592683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128755418d31'
down_revision = 'df4b56349cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('flow_order')

    # ### end Alembic commands ###
