"""drop material_requirements unique constraint

Revision ID: 18359fe21041
Revises: 8a7fce0bd5a8
Create Date: 2026-07-01 22:00:31.906994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18359fe21041'
down_revision = '8a7fce0bd5a8'
branch_labels = None
depends_on = None


def upgrade():
    # Drop and recreate without the unique constraint.
    # SQLite cannot drop constraints, so rebuild the table.
    op.drop_table('material_requirements')
    op.create_table(
        'material_requirements',
        sa.Column('id',                  sa.Integer(),    nullable=False),
        sa.Column('works_order',         sa.String(20),   nullable=True),
        sa.Column('job_released',        sa.Boolean(),    nullable=True),
        sa.Column('job_firm',            sa.Boolean(),    nullable=True),
        sa.Column('job_complete',        sa.Boolean(),    nullable=True),
        sa.Column('job_closed',          sa.Boolean(),    nullable=True),
        sa.Column('due_date',            sa.Date(),       nullable=True),
        sa.Column('finished_part_num',   sa.String(50),   nullable=True),
        sa.Column('finished_part_desc',  sa.String(200),  nullable=True),
        sa.Column('prod_qty',            sa.Numeric(14,3),nullable=True),
        sa.Column('plant',               sa.String(20),   nullable=True),
        sa.Column('prod_plnwk',          sa.String(20),   nullable=True),
        sa.Column('model',               sa.String(100),  nullable=True),
        sa.Column('size',                sa.String(50),   nullable=True),
        sa.Column('so_type',             sa.String(20),   nullable=True),
        sa.Column('so_number',           sa.String(20),   nullable=True),
        sa.Column('assembly_seq',        sa.Integer(),    nullable=True),
        sa.Column('assembly_desc',       sa.String(200),  nullable=True),
        sa.Column('mtl_seq',             sa.Integer(),    nullable=True),
        sa.Column('material_code',       sa.String(50),   nullable=True),
        sa.Column('material_description',sa.String(200),  nullable=True),
        sa.Column('backflush',           sa.Boolean(),    nullable=True),
        sa.Column('qty_per',             sa.Numeric(14,4),nullable=True),
        sa.Column('qty_for_order',       sa.Numeric(14,3),nullable=True),
        sa.Column('qty_issued',          sa.Numeric(14,3),nullable=True),
        sa.Column('issued_complete',     sa.Boolean(),    nullable=True),
        sa.Column('related_operation',   sa.Integer(),    nullable=True),
        sa.Column('warehouse_code',      sa.String(10),   nullable=True),
        sa.Column('class_id',            sa.String(50),   nullable=True),
        sa.Column('imported_at',         sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        # No unique constraint — BAQ can return same mtl_seq for multiple SOs
    )
    op.create_index('ix_material_requirements_works_order',   'material_requirements', ['works_order'])
    op.create_index('ix_material_requirements_due_date',      'material_requirements', ['due_date'])
    op.create_index('ix_material_requirements_material_code', 'material_requirements', ['material_code'])
    op.create_index('ix_material_requirements_so_number',     'material_requirements', ['so_number'])
    op.create_index('ix_material_requirements_job_closed',    'material_requirements', ['job_closed'])
    op.create_index('ix_material_requirements_plant',         'material_requirements', ['plant'])
    # ### end Alembic commands ###


def downgrade():
    pass  # No rollback needed — the constraint was wrong
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_mat_req_due_date')
        batch_op.drop_index('ix_mat_req_job_closed')
        batch_op.drop_index('ix_mat_req_material_code')
        batch_op.drop_index('ix_mat_req_plant')
        batch_op.drop_index('ix_mat_req_so_number')
        batch_op.drop_index('ix_mat_req_works_order')
        batch_op.drop_constraint('uq_mat_req', type_='unique')
        batch_op.create_index(batch_op.f('ix_material_requirements_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_finished_part_num'), ['finished_part_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_issued_complete'), ['issued_complete'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_job_closed'), ['job_closed'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_job_complete'), ['job_complete'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_material_code'), ['material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_plant'), ['plant'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_so_number'), ['so_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_works_order'), ['works_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_requirements_works_order'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_so_number'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_plant'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_material_code'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_job_complete'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_job_closed'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_issued_complete'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_finished_part_num'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_due_date'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_class_id'))
        batch_op.create_unique_constraint('uq_mat_req', ['works_order', 'assembly_seq', 'mtl_seq'])
        batch_op.create_index('ix_mat_req_works_order', ['works_order'], unique=False)
        batch_op.create_index('ix_mat_req_so_number', ['so_number'], unique=False)
        batch_op.create_index('ix_mat_req_plant', ['plant'], unique=False)
        batch_op.create_index('ix_mat_req_material_code', ['material_code'], unique=False)
        batch_op.create_index('ix_mat_req_job_closed', ['job_closed'], unique=False)
        batch_op.create_index('ix_mat_req_due_date', ['due_date'], unique=False)

    # ### end Alembic commands ###
