"""add_customer_groups_and_capacity_targets

Revision ID: 1f4d3532887f
Revises: 4b6eb0327713
Create Date: 2026-08-25 13:30:18.539407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4d3532887f'
down_revision = '4b6eb0327713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('colour', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_cg_name')
    )
    op.create_table('customer_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['customer_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', name='uq_cgm_customer_id')
    )
    with op.batch_alter_table('customer_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_group_members_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_group_members_group_id'), ['group_id'], unique=False)

    op.create_table('planning_capacity_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=True),
    sa.Column('target_per_day', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('max_per_day', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week', name='uq_cap_target_week')
    )
    with op.batch_alter_table('planning_capacity_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planning_capacity_targets_week'), ['week'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning_capacity_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planning_capacity_targets_week'))

    op.drop_table('planning_capacity_targets')
    with op.batch_alter_table('customer_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_group_members_group_id'))
        batch_op.drop_index(batch_op.f('ix_customer_group_members_customer_id'))

    op.drop_table('customer_group_members')
    op.drop_table('customer_groups')
    # ### end Alembic commands ###
