"""drop row_ident unique constraint

Revision ID: 376cc70dbd6e
Revises: 4587b490af08
Create Date: 2026-07-04 21:50:36.801444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376cc70dbd6e'
down_revision = '4587b490af08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_output', schema=None) as batch_op:
        batch_op.drop_index('ix_production_output_row_ident')
        batch_op.create_index(batch_op.f('ix_production_output_row_ident'), ['row_ident'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_output_row_ident'))
        batch_op.create_index('ix_production_output_row_ident', ['row_ident'], unique=1)

    # ### end Alembic commands ###
