"""add row_ident to production_output

Revision ID: 4587b490af08
Revises: d6725c1e972c
Create Date: 2026-07-04 21:34:25.206641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4587b490af08'
down_revision = 'd6725c1e972c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_ident', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_production_output_row_ident'), ['row_ident'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_output_row_ident'))
        batch_op.drop_column('row_ident')

    # ### end Alembic commands ###
