"""add_run_requested_to_sync_jobs

Revision ID: 4b41db2532de
Revises: ace5a406e1b9
Create Date: 2026-08-28 09:25:23.800011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b41db2532de'
down_revision = 'ace5a406e1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_requested', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_column('run_requested')

    # ### end Alembic commands ###
