"""add_planning_sessions_overrides_smv

Revision ID: 4b6eb0327713
Revises: b3f4a1c2d5e6
Create Date: 2026-08-25 11:40:57.989001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6eb0327713'
down_revision = 'b3f4a1c2d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('job_num', sa.String(length=20), nullable=False),
    sa.Column('assembly_seq', sa.Integer(), nullable=False),
    sa.Column('override_plnwk', sa.String(length=20), nullable=True),
    sa.Column('override_due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['planning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'job_num', 'assembly_seq', name='uq_override_session_job')
    )
    with op.batch_alter_table('planning_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planning_overrides_job_num'), ['job_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_planning_overrides_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smv_per_unit', sa.Numeric(precision=8, scale=4), nullable=True))

    with op.batch_alter_table('material_requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_mr_code_group')
        batch_op.drop_index('ix_mr_group_status')

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_so_identity')
        batch_op.drop_index('ix_so_open_due')

    with op.batch_alter_table('works_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_wo_asm_complete')
        batch_op.drop_index('ix_wo_job_asm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_orders', schema=None) as batch_op:
        batch_op.create_index('ix_wo_job_asm', ['job_num', 'assembly_seq'], unique=False)
        batch_op.create_index('ix_wo_asm_complete', ['assembly_seq', 'job_complete'], unique=False)

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index('ix_so_open_due', ['open_order', 'need_by_date'], unique=False)
        batch_op.create_index('ix_so_identity', ['order_num', 'order_line', 'rel_num'], unique=False)

    with op.batch_alter_table('material_requirements', schema=None) as batch_op:
        batch_op.create_index('ix_mr_group_status', ['material_group', 'job_closed', 'issued_complete'], unique=False)
        batch_op.create_index('ix_mr_code_group', ['material_code', 'material_group'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('smv_per_unit')

    with op.batch_alter_table('planning_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planning_overrides_session_id'))
        batch_op.drop_index(batch_op.f('ix_planning_overrides_job_num'))

    op.drop_table('planning_overrides')
    op.drop_table('planning_sessions')
    # ### end Alembic commands ###
