"""add release decision snapshot identity columns

Revision ID: 4c4f1305e59c
Revises: b7434022137c
Create Date: 2026-09-25 12:39:35.403015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4f1305e59c'
down_revision = 'b7434022137c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_jobs_unlocked_keys', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_orders_unlocked_keys', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release_decisions', schema=None) as batch_op:
        batch_op.drop_column('snapshot_orders_unlocked_keys')
        batch_op.drop_column('snapshot_jobs_unlocked_keys')

    # ### end Alembic commands ###
