"""multi_site_restructure

Revision ID: 4de04c13aede
Revises: b3c4d5e6f7a8
Create Date: 2026-04-29 15:06:49.651924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de04c13aede'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_sites_is_active'), ['is_active'], unique=False)

    op.create_table('user_sites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'site_id')
    )
    with op.batch_alter_table('material_requirements_aftersales', schema=None) as batch_op:
        batch_op.drop_index('ix_material_requirements_aftersales_department')
        batch_op.drop_index('ix_material_requirements_aftersales_due_date')
        batch_op.drop_index('ix_material_requirements_aftersales_order_number')
        batch_op.drop_index('ix_material_requirements_aftersales_product_code')

    op.drop_table('material_requirements_aftersales')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_departments_code')
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_site_id'), ['site_id'], unique=False)
        batch_op.create_unique_constraint('uq_dept_site_code', ['site_id', 'code'])
        batch_op.create_foreign_key('fk_departments_site_id', 'sites', ['site_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_import_batches_site_id'), ['site_id'], unique=False)
        batch_op.create_foreign_key('fk_import_batches_site_id', 'sites', ['site_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('material_requirements_main', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_material_requirements_main_site_id'), ['site_id'], unique=False)
        batch_op.create_foreign_key('fk_mat_req_main_site_id', 'sites', ['site_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_po_line', type_='unique')
        batch_op.create_index(batch_op.f('ix_purchase_orders_site_id'), ['site_id'], unique=False)
        batch_op.create_unique_constraint('uq_po_site_line', ['site_id', 'po_number', 'line_number'])
        batch_op.create_foreign_key('fk_purchase_orders_site_id', 'sites', ['site_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('routing_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_routing_templates_site_id'), ['site_id'], unique=False)
        batch_op.create_foreign_key('fk_routing_templates_site_id', 'sites', ['site_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_sales_order_lines_caravan_code')
        batch_op.drop_constraint('uq_sol_so_line', type_='unique')
        batch_op.create_index(batch_op.f('ix_sales_order_lines_site_id'), ['site_id'], unique=False)
        batch_op.create_unique_constraint('uq_sol_site_so_line', ['site_id', 'so_number', 'line_number'])
        batch_op.create_foreign_key('fk_sales_order_lines_site_id', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('caravan_description')
        batch_op.drop_column('caravan_code')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_stock_product_code')
        batch_op.create_index(batch_op.f('ix_stock_product_code'), ['product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_site_id'), ['site_id'], unique=False)
        batch_op.create_unique_constraint('uq_stock_site_product', ['site_id', 'product_code'])
        batch_op.create_foreign_key('fk_stock_site_id', 'sites', ['site_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_stock_site_product', type_='unique')
        batch_op.drop_index(batch_op.f('ix_stock_site_id'))
        batch_op.drop_index(batch_op.f('ix_stock_product_code'))
        batch_op.create_index('ix_stock_product_code', ['product_code'], unique=1)
        batch_op.drop_column('site_id')

    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caravan_code', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('caravan_description', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_sol_site_so_line', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_site_id'))
        batch_op.create_unique_constraint('uq_sol_so_line', ['so_number', 'line_number'])
        batch_op.create_index('ix_sales_order_lines_caravan_code', ['caravan_code'], unique=False)
        batch_op.drop_column('site_id')

    with op.batch_alter_table('routing_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_routing_templates_site_id'))
        batch_op.drop_column('site_id')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_po_site_line', type_='unique')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_site_id'))
        batch_op.create_unique_constraint('uq_po_line', ['po_number', 'line_number'])
        batch_op.drop_column('site_id')

    with op.batch_alter_table('material_requirements_main', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_material_requirements_main_site_id'))
        batch_op.drop_column('site_id')

    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_import_batches_site_id'))
        batch_op.drop_column('site_id')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_dept_site_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_departments_site_id'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))
        batch_op.create_index('ix_departments_code', ['code'], unique=1)
        batch_op.drop_column('site_id')

    op.create_table('material_requirements_aftersales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('customer_product_ref', sa.VARCHAR(length=50), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('load_date', sa.DATE(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('product_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('qty_required', sa.NUMERIC(precision=12, scale=3), nullable=True),
    sa.Column('imported_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_requirements_aftersales', schema=None) as batch_op:
        batch_op.create_index('ix_material_requirements_aftersales_product_code', ['product_code'], unique=False)
        batch_op.create_index('ix_material_requirements_aftersales_order_number', ['order_number'], unique=False)
        batch_op.create_index('ix_material_requirements_aftersales_due_date', ['due_date'], unique=False)
        batch_op.create_index('ix_material_requirements_aftersales_department', ['department'], unique=False)

    op.drop_table('user_sites')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_is_active'))
        batch_op.drop_index(batch_op.f('ix_sites_code'))

    op.drop_table('sites')
    # ### end Alembic commands ###
