"""initial_clean_schema

Revision ID: 52e643958385
Revises: 
Create Date: 2026-04-29 16:40:37.736534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e643958385'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_sites_is_active'), ['is_active'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_hours_per_day', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('flow_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'code', name='uq_dept_site_code')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_site_id'), ['site_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('import_type', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_closed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_import_type'), ['import_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_site_id'), ['site_id'], unique=False)

    op.create_table('material_requirements_main',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.String(length=30), nullable=True),
    sa.Column('batch_id', sa.String(length=30), nullable=True),
    sa.Column('so_number', sa.String(length=20), nullable=True),
    sa.Column('works_order', sa.String(length=50), nullable=True),
    sa.Column('load_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('material_code', sa.String(length=50), nullable=True),
    sa.Column('material_description', sa.String(length=200), nullable=True),
    sa.Column('qty_required_per_set', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('qty_for_order', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('qty_issued', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('product_group', sa.String(length=30), nullable=True),
    sa.Column('product_group_desc', sa.String(length=100), nullable=True),
    sa.Column('complete', sa.String(length=1), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_requirements_main', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_requirements_main_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_main_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_main_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_main_material_code'), ['material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_main_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_main_so_number'), ['so_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requirements_main_works_order'), ['works_order'], unique=False)

    op.create_table('mrp_exempt_materials',
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('exempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exempted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exempted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('material_code')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('outstanding_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('supplier_code', sa.String(length=30), nullable=True),
    sa.Column('supplier_name', sa.String(length=100), nullable=True),
    sa.Column('po_type', sa.String(length=20), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'po_number', 'line_number', name='uq_po_site_line')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_product_code'), ['product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_site_id'), ['site_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sales_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('so_number', sa.String(length=20), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('customer_order_ref', sa.String(length=50), nullable=True),
    sa.Column('customer_product_ref', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=30), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('product_description', sa.String(length=200), nullable=True),
    sa.Column('qty_ordered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('ops_missing', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ops_missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('despatch_completed_date', sa.Date(), nullable=True),
    sa.Column('order_completed_date', sa.Date(), nullable=True),
    sa.Column('production_ready_date', sa.Date(), nullable=True),
    sa.Column('customer_hold', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('customer_hold_since', sa.Date(), nullable=True),
    sa.Column('customer_hold_note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'so_number', 'line_number', name='uq_sol_site_so_line')
    )
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_lines_customer_code'), ['customer_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_customer_hold'), ['customer_hold'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_despatch_completed_date'), ['despatch_completed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_ops_missing'), ['ops_missing'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_order_completed_date'), ['order_completed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_planned_date'), ['planned_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_product_code'), ['product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_production_ready_date'), ['production_ready_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_so_number'), ['so_number'], unique=False)

    op.create_table('so_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('so_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_so_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_so_comments_so_number'), ['so_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_so_comments_user_id'), ['user_id'], unique=False)

    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('qty_on_hand', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'product_code', name='uq_stock_site_product')
    )
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_product_code'), ['product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_site_id'), ['site_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_sites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'site_id')
    )
    op.create_table('capacity_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=True),
    sa.Column('is_workday', sa.Boolean(), nullable=False),
    sa.Column('day_complete', sa.Boolean(), nullable=False),
    sa.Column('available_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('manually_overridden', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'date', name='uq_bucket_dept_date')
    )
    with op.batch_alter_table('capacity_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capacity_buckets_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_capacity_buckets_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capacity_buckets_week'), ['week'], unique=False)

    op.create_table('smv_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=100), nullable=False),
    sa.Column('timing_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('smv_minutes', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('ops', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'department_id', name='uq_smv_comp_dept')
    )
    with op.batch_alter_table('smv_matrix', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smv_matrix_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_smv_matrix_department_id'), ['department_id'], unique=False)

    op.create_table('works_order_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('so_number', sa.String(length=20), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('work_centre_name', sa.String(length=100), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('so_number', 'line_number', 'work_centre_name', name='uq_woo_key')
    )
    with op.batch_alter_table('works_order_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_works_order_operations_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_order_operations_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_order_operations_planned_date'), ['planned_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_order_operations_sales_order_line_id'), ['sales_order_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_order_operations_so_number'), ['so_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_order_operations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_order_operations_work_centre_name'), ['work_centre_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_order_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_order_operations_work_centre_name'))
        batch_op.drop_index(batch_op.f('ix_works_order_operations_status'))
        batch_op.drop_index(batch_op.f('ix_works_order_operations_so_number'))
        batch_op.drop_index(batch_op.f('ix_works_order_operations_sales_order_line_id'))
        batch_op.drop_index(batch_op.f('ix_works_order_operations_planned_date'))
        batch_op.drop_index(batch_op.f('ix_works_order_operations_due_date'))
        batch_op.drop_index(batch_op.f('ix_works_order_operations_department_id'))

    op.drop_table('works_order_operations')
    with op.batch_alter_table('smv_matrix', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smv_matrix_department_id'))
        batch_op.drop_index(batch_op.f('ix_smv_matrix_component_id'))

    op.drop_table('smv_matrix')
    with op.batch_alter_table('capacity_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capacity_buckets_week'))
        batch_op.drop_index(batch_op.f('ix_capacity_buckets_department_id'))
        batch_op.drop_index(batch_op.f('ix_capacity_buckets_date'))

    op.drop_table('capacity_buckets')
    op.drop_table('user_sites')
    op.drop_table('user_roles')
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_site_id'))
        batch_op.drop_index(batch_op.f('ix_stock_product_code'))

    op.drop_table('stock')
    with op.batch_alter_table('so_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_so_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_so_comments_so_number'))
        batch_op.drop_index(batch_op.f('ix_so_comments_created_at'))

    op.drop_table('so_comments')
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_so_number'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_site_id'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_production_ready_date'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_product_code'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_planned_date'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_order_type'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_order_completed_date'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_ops_missing'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_due_date'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_despatch_completed_date'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_customer_hold'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_customer_code'))

    op.drop_table('sales_order_lines')
    op.drop_table('role_permissions')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_site_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_product_code'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_due_date'))

    op.drop_table('purchase_orders')
    op.drop_table('mrp_exempt_materials')
    with op.batch_alter_table('material_requirements_main', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_requirements_main_works_order'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_main_so_number'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_main_site_id'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_main_material_code'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_main_due_date'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_main_department'))
        batch_op.drop_index(batch_op.f('ix_material_requirements_main_customer_id'))

    op.drop_table('material_requirements_main')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_site_id'))
        batch_op.drop_index(batch_op.f('ix_import_batches_import_type'))

    op.drop_table('import_batches')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_site_id'))
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('system_settings')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_is_active'))
        batch_op.drop_index(batch_op.f('ix_sites_code'))

    op.drop_table('sites')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_module'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
