"""initial

Revision ID: 69045f3f9a99
Revises: 
Create Date: 2026-03-09 15:40:55.868489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69045f3f9a99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_product_code', sa.String(length=50), nullable=False),
    sa.Column('component_product_code', sa.String(length=50), nullable=False),
    sa.Column('quantity_per', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=True),
    sa.Column('scrap_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boms_component_product_code'), ['component_product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_boms_parent_product_code'), ['parent_product_code'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=True),
    sa.Column('stock_on_hand', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_materials_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_supplier_code'), ['supplier_code'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('routings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('revision', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routings_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_routings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_routings_product_code'), ['product_code'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('work_centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hours_per_shift', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shifts_per_day', sa.Integer(), nullable=True),
    sa.Column('efficiency_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_centres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_centres_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_centres_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_centres_is_active'), ['is_active'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('capacity_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_centre_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('available_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('allocated_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['work_centre_id'], ['work_centres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_centre_id', 'period_start', name='uq_bucket_wc_period')
    )
    with op.batch_alter_table('capacity_buckets', schema=None) as batch_op:
        batch_op.create_index('ix_bucket_period', ['period_start', 'period_end'], unique=False)

    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('work_centre_id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('setup_time_hrs', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('run_time_hrs', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_centre_id'], ['work_centres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routing_id', 'sequence_no', name='uq_op_routing_seq')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_expected_date'), ['expected_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_status'), ['status'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_description', sa.String(length=200), nullable=True),
    sa.Column('routing_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_completed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_orders_planned_end'), ['planned_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_planned_start'), ['planned_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_product_code'), ['product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_status'), ['status'], unique=False)

    op.create_table('forecast_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('forecast_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'product_code', 'period_start', name='uq_forecast_item')
    )
    with op.batch_alter_table('forecast_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_items_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_items_product_code'), ['product_code'], unique=False)

    op.create_table('scenario_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workload_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('work_centre_id', sa.Integer(), nullable=True),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_centre_id'], ['work_centres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workload_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workload_assignments_assignment_date'), ['assignment_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workload_assignments_assignment_date'))

    op.drop_table('workload_assignments')
    op.drop_table('scenario_assumptions')
    with op.batch_alter_table('forecast_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_items_product_code'))
        batch_op.drop_index(batch_op.f('ix_forecast_items_period_start'))

    op.drop_table('forecast_items')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_status'))
        batch_op.drop_index(batch_op.f('ix_work_orders_product_code'))
        batch_op.drop_index(batch_op.f('ix_work_orders_planned_start'))
        batch_op.drop_index(batch_op.f('ix_work_orders_planned_end'))
        batch_op.drop_index(batch_op.f('ix_work_orders_order_number'))

    op.drop_table('work_orders')
    op.drop_table('user_roles')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_status'))

    op.drop_table('scenarios')
    op.drop_table('role_permissions')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_expected_date'))

    op.drop_table('purchase_orders')
    op.drop_table('operations')
    op.drop_table('forecast_runs')
    with op.batch_alter_table('capacity_buckets', schema=None) as batch_op:
        batch_op.drop_index('ix_bucket_period')

    op.drop_table('capacity_buckets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('work_centres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_centres_is_active'))
        batch_op.drop_index(batch_op.f('ix_work_centres_department'))
        batch_op.drop_index(batch_op.f('ix_work_centres_code'))

    op.drop_table('work_centres')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_code'))

    op.drop_table('teams')
    with op.batch_alter_table('routings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routings_product_code'))
        batch_op.drop_index(batch_op.f('ix_routings_is_active'))
        batch_op.drop_index(batch_op.f('ix_routings_code'))

    op.drop_table('routings')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_module'))

    op.drop_table('permissions')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_materials_is_active'))
        batch_op.drop_index(batch_op.f('ix_materials_code'))

    op.drop_table('materials')
    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boms_parent_product_code'))
        batch_op.drop_index(batch_op.f('ix_boms_component_product_code'))

    op.drop_table('boms')
    # ### end Alembic commands ###
