"""add sales_orders table

Revision ID: 6a3ec5fd7880
Revises: f6ad7d05b5e9
Create Date: 2026-07-04 21:12:10.270437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3ec5fd7880'
down_revision = 'f6ad7d05b5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('order_line', sa.Integer(), nullable=False),
    sa.Column('rel_num', sa.Integer(), nullable=False),
    sa.Column('po_num', sa.String(length=50), nullable=True),
    sa.Column('open_order', sa.Boolean(), nullable=True),
    sa.Column('open_line', sa.Boolean(), nullable=True),
    sa.Column('open_release', sa.Boolean(), nullable=True),
    sa.Column('firm_order', sa.Boolean(), nullable=True),
    sa.Column('firm_line', sa.Boolean(), nullable=True),
    sa.Column('firm_release', sa.Boolean(), nullable=True),
    sa.Column('void_line', sa.Boolean(), nullable=True),
    sa.Column('order_held', sa.Boolean(), nullable=True),
    sa.Column('so_credit_hold', sa.Boolean(), nullable=True),
    sa.Column('customer_credit_hold', sa.Boolean(), nullable=True),
    sa.Column('guaranteed_christmas', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Boolean(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('need_by_date', sa.Date(), nullable=True),
    sa.Column('req_date', sa.Date(), nullable=True),
    sa.Column('original_ship_by', sa.Date(), nullable=True),
    sa.Column('original_need_by', sa.Date(), nullable=True),
    sa.Column('order_received_date', sa.Date(), nullable=True),
    sa.Column('customer_delivery_requested', sa.Date(), nullable=True),
    sa.Column('last_xmas_order_date', sa.Date(), nullable=True),
    sa.Column('last_xmas_delivery', sa.Date(), nullable=True),
    sa.Column('order_ack_sent', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('customer_country', sa.String(length=100), nullable=True),
    sa.Column('customer_group', sa.String(length=50), nullable=True),
    sa.Column('ship_to_num', sa.String(length=20), nullable=True),
    sa.Column('sales_rep', sa.String(length=50), nullable=True),
    sa.Column('sur_name', sa.String(length=100), nullable=True),
    sa.Column('so_type', sa.String(length=20), nullable=True),
    sa.Column('so_type_desc', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('prod_code', sa.String(length=50), nullable=True),
    sa.Column('entry_person', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('job_num', sa.String(length=20), nullable=True),
    sa.Column('job_released', sa.Boolean(), nullable=True),
    sa.Column('job_firm', sa.Boolean(), nullable=True),
    sa.Column('prod_plnwk', sa.String(length=20), nullable=True),
    sa.Column('assembly_seq', sa.Integer(), nullable=True),
    sa.Column('part_num', sa.String(length=50), nullable=True),
    sa.Column('part_desc', sa.String(length=255), nullable=True),
    sa.Column('base_part_num', sa.String(length=50), nullable=True),
    sa.Column('xpart_num', sa.String(length=50), nullable=True),
    sa.Column('ium', sa.String(length=10), nullable=True),
    sa.Column('wip_bin', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('size_desc', sa.String(length=100), nullable=True),
    sa.Column('prod_size', sa.String(length=100), nullable=True),
    sa.Column('cover', sa.String(length=50), nullable=True),
    sa.Column('cover_desc', sa.String(length=100), nullable=True),
    sa.Column('leg', sa.String(length=100), nullable=True),
    sa.Column('leg_mtl', sa.String(length=50), nullable=True),
    sa.Column('castor_mtl', sa.String(length=50), nullable=True),
    sa.Column('stud1_mtl', sa.String(length=50), nullable=True),
    sa.Column('stud2_mtl', sa.String(length=50), nullable=True),
    sa.Column('seat_interior_mtl', sa.String(length=50), nullable=True),
    sa.Column('back_interior_mtl', sa.String(length=50), nullable=True),
    sa.Column('scat_interior_mtl', sa.String(length=50), nullable=True),
    sa.Column('material_1', sa.String(length=50), nullable=True),
    sa.Column('material_1_desc', sa.String(length=100), nullable=True),
    sa.Column('material_2', sa.String(length=50), nullable=True),
    sa.Column('material_2_desc', sa.String(length=100), nullable=True),
    sa.Column('material_3', sa.String(length=50), nullable=True),
    sa.Column('material_3_desc', sa.String(length=100), nullable=True),
    sa.Column('material_4', sa.String(length=50), nullable=True),
    sa.Column('material_4_desc', sa.String(length=100), nullable=True),
    sa.Column('material_5', sa.String(length=50), nullable=True),
    sa.Column('material_5_desc', sa.String(length=100), nullable=True),
    sa.Column('material_6', sa.String(length=50), nullable=True),
    sa.Column('material_6_desc', sa.String(length=100), nullable=True),
    sa.Column('material_7', sa.String(length=50), nullable=True),
    sa.Column('material_7_desc', sa.String(length=100), nullable=True),
    sa.Column('material_8', sa.String(length=50), nullable=True),
    sa.Column('material_8_desc', sa.String(length=100), nullable=True),
    sa.Column('selling_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('shipped_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('required_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('qty_completed', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('release_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('release_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('release_price_gbp', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('order_book_comments', sa.Text(), nullable=True),
    sa.Column('ship_by_changed_count', sa.Integer(), nullable=True),
    sa.Column('need_by_changed_count', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_num', 'order_line', 'rel_num', name='uq_so_num_line_rel')
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_orders_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_customer_group'), ['customer_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_job_num'), ['job_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_need_by_date'), ['need_by_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_open_order'), ['open_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_order_num'), ['order_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_part_num'), ['part_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_prod_code'), ['prod_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_prod_plnwk'), ['prod_plnwk'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_so_type'), ['so_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_so_type'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_prod_plnwk'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_prod_code'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_part_num'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_order_num'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_order_date'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_open_order'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_need_by_date'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_job_num'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_customer_group'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_channel'))

    op.drop_table('sales_orders')
    # ### end Alembic commands ###
