"""remove sales_orders unique constraint

Revision ID: 7377d5c4ec66
Revises: 054eedd45db9
Create Date: 2026-07-04 21:15:53.453175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7377d5c4ec66'
down_revision = '054eedd45db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_orders_customer')
        batch_op.drop_index('ix_sales_orders_need_by')
        batch_op.drop_constraint('uq_so_num_line_rel_asm', type_='unique')
        batch_op.create_index(batch_op.f('ix_sales_orders_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_customer_group'), ['customer_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_need_by_date'), ['need_by_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_prod_code'), ['prod_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_so_type'), ['so_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_so_type'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_prod_code'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_need_by_date'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_customer_group'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_channel'))
        batch_op.create_unique_constraint('uq_so_num_line_rel_asm', ['order_num', 'order_line', 'rel_num', 'assembly_seq'])
        batch_op.create_index('ix_sales_orders_need_by', ['need_by_date'], unique=False)
        batch_op.create_index('ix_sales_orders_customer', ['customer_id'], unique=False)

    # ### end Alembic commands ###
