"""add_sync_schedules_table

Revision ID: 887ed3e7aca3
Revises: 9dfe64b0182f
Create Date: 2026-07-20 23:53:49.171620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887ed3e7aca3'
down_revision = '9dfe64b0182f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importer_key', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_row_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_schedules_importer_key'), ['importer_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_schedules_importer_key'))

    op.drop_table('sync_schedules')
    # ### end Alembic commands ###
