"""add_track_to_departments

Revision ID: 8bf01c116d63
Revises: 376cc70dbd6e
Create Date: 2026-07-04 23:29:54.619690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf01c116d63'
down_revision = '376cc70dbd6e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('track')

    # ### end Alembic commands ###
