"""redesign purchase_orders for epicor api

Revision ID: 8cd035ed33b9
Revises: d89ae9b4e049
Create Date: 2026-07-01 20:50:11.191284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd035ed33b9'
down_revision = 'd89ae9b4e049'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('purchase_orders')
    op.create_table(
        'purchase_orders',
        sa.Column('id',             sa.Integer(),       nullable=False),
        sa.Column('po_num',         sa.Integer(),       nullable=False),
        sa.Column('po_line',        sa.Integer(),       nullable=False),
        sa.Column('po_release',     sa.Integer(),       nullable=False),
        sa.Column('open_order',     sa.Boolean(),       nullable=True),
        sa.Column('open_line',      sa.Boolean(),       nullable=True),
        sa.Column('open_release',   sa.Boolean(),       nullable=True),
        sa.Column('order_date',     sa.Date(),          nullable=True),
        sa.Column('due_date',       sa.Date(),          nullable=True),
        sa.Column('promise_date',   sa.Date(),          nullable=True),
        sa.Column('part_num',       sa.String(50),      nullable=True),
        sa.Column('line_desc',      sa.String(255),     nullable=True),
        sa.Column('unit_of_measure',sa.String(10),      nullable=True),
        sa.Column('rel_qty',        sa.Numeric(14, 3),  nullable=True),
        sa.Column('arrived_qty',    sa.Numeric(14, 3),  nullable=True),
        sa.Column('received_qty',   sa.Numeric(14, 3),  nullable=True),
        sa.Column('outstanding_qty',sa.Numeric(14, 3),  nullable=True),
        sa.Column('invoiced_qty',   sa.Numeric(14, 3),  nullable=True),
        sa.Column('unit_cost',      sa.Numeric(14, 4),  nullable=True),
        sa.Column('doc_unit_cost',  sa.Numeric(14, 4),  nullable=True),
        sa.Column('cost_per_code',  sa.String(5),       nullable=True),
        sa.Column('currency_code',  sa.String(10),      nullable=True),
        sa.Column('exchange_rate',  sa.Numeric(12, 6),  nullable=True),
        sa.Column('supplier_id',    sa.String(20),      nullable=True),
        sa.Column('supplier_name',  sa.String(150),     nullable=True),
        sa.Column('imported_at',    sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('po_num', 'po_line', 'po_release', name='uq_po_num_line_rel'),
    )
    op.create_index('ix_purchase_orders_po_num',         'purchase_orders', ['po_num'])
    op.create_index('ix_purchase_orders_part_num',       'purchase_orders', ['part_num'])
    op.create_index('ix_purchase_orders_due_date',       'purchase_orders', ['due_date'])
    op.create_index('ix_purchase_orders_outstanding_qty','purchase_orders', ['outstanding_qty'])
    op.create_index('ix_purchase_orders_supplier_id',    'purchase_orders', ['supplier_id'])
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('purchase_orders')
    op.create_table(
        'purchase_orders',
        sa.Column('id',           sa.Integer(),      nullable=False),
        sa.Column('site_id',      sa.Integer(),      nullable=True),
        sa.Column('po_number',    sa.String(30),     nullable=False),
        sa.Column('line_number',  sa.Integer(),      nullable=False),
        sa.Column('product_code', sa.String(50),     nullable=True),
        sa.Column('description',  sa.String(200),    nullable=True),
        sa.Column('outstanding_qty', sa.Numeric(12, 3), nullable=True),
        sa.Column('due_date',     sa.Date(),         nullable=True),
        sa.Column('supplier_code',sa.String(30),     nullable=True),
        sa.Column('supplier_name',sa.String(100),    nullable=True),
        sa.Column('po_type',      sa.String(20),     nullable=True),
        sa.Column('imported_at',  sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_purchase_orders_site_id',      'purchase_orders', ['site_id'])
    op.create_index('ix_purchase_orders_product_code', 'purchase_orders', ['product_code'])
    op.create_index('ix_purchase_orders_po_number',    'purchase_orders', ['po_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('line_number', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('product_code', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('po_number', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('supplier_code', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('po_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_po_num_line_rel', type_='unique')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_num'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_part_num'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_outstanding_qty'))
        batch_op.create_unique_constraint('uq_po_site_line', ['site_id', 'po_number', 'line_number'])
        batch_op.create_index('ix_purchase_orders_site_id', ['site_id'], unique=False)
        batch_op.create_index('ix_purchase_orders_product_code', ['product_code'], unique=False)
        batch_op.create_index('ix_purchase_orders_po_number', ['po_number'], unique=False)
        batch_op.alter_column('supplier_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('outstanding_qty',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.NUMERIC(precision=12, scale=3),
               existing_nullable=True)
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency_code')
        batch_op.drop_column('cost_per_code')
        batch_op.drop_column('doc_unit_cost')
        batch_op.drop_column('unit_cost')
        batch_op.drop_column('invoiced_qty')
        batch_op.drop_column('received_qty')
        batch_op.drop_column('arrived_qty')
        batch_op.drop_column('rel_qty')
        batch_op.drop_column('unit_of_measure')
        batch_op.drop_column('line_desc')
        batch_op.drop_column('part_num')
        batch_op.drop_column('promise_date')
        batch_op.drop_column('order_date')
        batch_op.drop_column('open_release')
        batch_op.drop_column('open_line')
        batch_op.drop_column('open_order')
        batch_op.drop_column('po_release')
        batch_op.drop_column('po_line')
        batch_op.drop_column('po_num')

    # ### end Alembic commands ###
