"""add op_code to departments

Revision ID: 9dfe64b0182f
Revises: 96d9be241aa7
Create Date: 2026-07-20 22:02:32.159924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfe64b0182f'
down_revision = '96d9be241aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('op_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_departments_op_code'), ['op_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_op_code'))
        batch_op.drop_column('op_code')

    # ### end Alembic commands ###
