"""widen_cover_type_so_type_desc_to_text

Revision ID: a3ad48d37832
Revises: 0f47e4fa277e
Create Date: 2026-07-29 11:29:01.713043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ad48d37832'
down_revision = '0f47e4fa277e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.alter_column('so_type_desc',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('works_orders', schema=None) as batch_op:
        batch_op.alter_column('so_type_desc',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('cover_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_orders', schema=None) as batch_op:
        batch_op.alter_column('cover_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('so_type_desc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.alter_column('so_type_desc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
