"""add_customer_group_capacity_targets

Revision ID: ace5a406e1b9
Revises: fdb0e49d7fa3
Create Date: 2026-08-25 14:11:37.597197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace5a406e1b9'
down_revision = 'fdb0e49d7fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_group_capacity_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('weekly_capacity', sa.Numeric(precision=8, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['customer_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'week', name='uq_cgct_group_week')
    )
    with op.batch_alter_table('customer_group_capacity_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_group_capacity_targets_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_group_capacity_targets_week'), ['week'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_group_capacity_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_group_capacity_targets_week'))
        batch_op.drop_index(batch_op.f('ix_customer_group_capacity_targets_group_id'))

    op.drop_table('customer_group_capacity_targets')
    # ### end Alembic commands ###
