"""add despatch_completed_date and order_completed_date to sales_order_lines

Revision ID: b2eab7dc1fff
Revises: 80ec2ad9a620
Create Date: 2026-03-18 08:26:59.013736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2eab7dc1fff'
down_revision = '80ec2ad9a620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('despatch_completed_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('order_completed_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_order_lines_despatch_completed_date'), ['despatch_completed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_order_completed_date'), ['order_completed_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_order_completed_date'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_despatch_completed_date'))
        batch_op.drop_column('order_completed_date')
        batch_op.drop_column('despatch_completed_date')

    # ### end Alembic commands ###
