"""add material class labels

Revision ID: b4bf53eef721
Revises: 5c92e1a0f3b7
Create Date: 2026-09-24 13:11:34.024195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bf53eef721'
down_revision = '5c92e1a0f3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_class_labels',
    sa.Column('class_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_class_labels')
    # ### end Alembic commands ###
