"""add release_decisions table

Revision ID: b7434022137c
Revises: b4bf53eef721
Create Date: 2026-09-25 11:53:12.523468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7434022137c'
down_revision = 'b4bf53eef721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_num', sa.Integer(), nullable=False),
    sa.Column('po_line', sa.Integer(), nullable=False),
    sa.Column('po_release', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('staged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_reason', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('snapshot_cash_proxy', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('snapshot_jobs_unlocked', sa.Integer(), nullable=True),
    sa.Column('snapshot_orders_unlocked', sa.Integer(), nullable=True),
    sa.Column('snapshot_order_value_unlocked', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('snapshot_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['committed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_num', 'po_line', 'po_release', name='uq_release_decision_po')
    )
    with op.batch_alter_table('release_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_decisions_po_num'), ['po_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_decisions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_decisions_status'))
        batch_op.drop_index(batch_op.f('ix_release_decisions_po_num'))

    op.drop_table('release_decisions')
    # ### end Alembic commands ###
