"""add so_comments table

Revision ID: d61b009f901f
Revises: c3d4e5f6a7b8
Create Date: 2026-03-16 13:01:45.314527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61b009f901f'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('so_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('so_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_so_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_so_comments_so_number'), ['so_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_so_comments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('so_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_so_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_so_comments_so_number'))
        batch_op.drop_index(batch_op.f('ix_so_comments_created_at'))

    op.drop_table('so_comments')
    # ### end Alembic commands ###
