"""add production_output table

Revision ID: d6725c1e972c
Revises: 7377d5c4ec66
Create Date: 2026-07-04 21:29:23.967953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6725c1e972c'
down_revision = '7377d5c4ec66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_num', sa.String(length=20), nullable=True),
    sa.Column('assembly_seq', sa.Integer(), nullable=True),
    sa.Column('opr_seq', sa.Integer(), nullable=True),
    sa.Column('op_desc', sa.String(length=50), nullable=True),
    sa.Column('employee_num', sa.String(length=20), nullable=True),
    sa.Column('labor_entry_method', sa.String(length=20), nullable=True),
    sa.Column('clock_in_date', sa.Date(), nullable=True),
    sa.Column('labor_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('prod_plnwk', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('mod_size', sa.String(length=100), nullable=True),
    sa.Column('line_desc', sa.String(length=255), nullable=True),
    sa.Column('assembly_desc', sa.String(length=200), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('release_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('release_discount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('misc_charges', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('release_total', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('release_total_gbp', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_output', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_output_clock_in_date'), ['clock_in_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_output_employee_num'), ['employee_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_output_job_num'), ['job_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_output_op_desc'), ['op_desc'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_output_prod_plnwk'), ['prod_plnwk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_output_prod_plnwk'))
        batch_op.drop_index(batch_op.f('ix_production_output_op_desc'))
        batch_op.drop_index(batch_op.f('ix_production_output_job_num'))
        batch_op.drop_index(batch_op.f('ix_production_output_employee_num'))
        batch_op.drop_index(batch_op.f('ix_production_output_clock_in_date'))

    op.drop_table('production_output')
    # ### end Alembic commands ###
