"""add routing models and dept default_lead_time_days

Revision ID: df4b56349cc1
Revises: f74efd05d3cd
Create Date: 2026-03-10 14:10:45.710452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4b56349cc1'
down_revision = 'f74efd05d3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routing_template_id'], ['routing_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_stages_routing_template_id'), ['routing_template_id'], unique=False)

    op.create_table('routing_stage_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_stage_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('lead_time_override_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routing_stage_id'], ['routing_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routing_stage_id', 'department_id', name='uq_rse_stage_dept')
    )
    with op.batch_alter_table('routing_stage_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_stage_entries_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routing_stage_entries_routing_stage_id'), ['routing_stage_id'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_lead_time_days', sa.Integer(), server_default='2', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('default_lead_time_days')

    with op.batch_alter_table('routing_stage_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_stage_entries_routing_stage_id'))
        batch_op.drop_index(batch_op.f('ix_routing_stage_entries_department_id'))

    op.drop_table('routing_stage_entries')
    with op.batch_alter_table('routing_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_stages_routing_template_id'))

    op.drop_table('routing_stages')
    op.drop_table('routing_templates')
    # ### end Alembic commands ###
