"""add_is_open_to_sales_order_lines

Revision ID: e143896d2c9d
Revises: 0b24a2023d7a
Create Date: 2026-04-30 09:36:57.910604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e143896d2c9d'
down_revision = '0b24a2023d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_open', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_order_lines_is_open'), ['is_open'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_is_open'))
        batch_op.drop_column('is_open')

    # ### end Alembic commands ###
