"""add_schedule_params_to_sync_schedules

Revision ID: e618cf98adba
Revises: 887ed3e7aca3
Create Date: 2026-07-20 23:59:13.793575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e618cf98adba'
down_revision = '887ed3e7aca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_params', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_schedules', schema=None) as batch_op:
        batch_op.drop_column('schedule_params')

    # ### end Alembic commands ###
