"""add ops_missing to sales_order_lines

Revision ID: f511ef33295b
Revises: b2eab7dc1fff
Create Date: 2026-03-18 15:06:28.527417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f511ef33295b'
down_revision = 'b2eab7dc1fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ops_missing', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ops_missing_since', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_order_lines_ops_missing'), ['ops_missing'], unique=False)

    # Backfill: flag existing SOLs that have no associated WOO rows at all
    op.execute("""
        UPDATE sales_order_lines
        SET ops_missing = 1
        WHERE id NOT IN (
            SELECT DISTINCT sales_order_line_id FROM works_order_operations
        )
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_ops_missing'))
        batch_op.drop_column('ops_missing_since')
        batch_op.drop_column('ops_missing')

    # ### end Alembic commands ###
