"""expand works_orders with all BAQ fields

Revision ID: f6ad7d05b5e9
Revises: f97dbf999fe9
Create Date: 2026-07-04 20:54:49.097272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ad7d05b5e9'
down_revision = 'f97dbf999fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firm_order', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('firm_line', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('order_held', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('so_credit_hold', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('customer_credit_hold', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ship_order_complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('guaranteed_christmas', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('display_order', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('original_ship_by', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('original_need_by', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('customer_delivery_requested', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('order_received_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_xmas_order_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_xmas_delivery', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('order_sort', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('so_type_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('order_rel_num', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ship_to_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('ship_to_zip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('order_book_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('grn', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('net_unit_price', sa.Numeric(precision=14, scale=4), nullable=True))
        batch_op.add_column(sa.Column('net_unit_price_gbp', sa.Numeric(precision=14, scale=4), nullable=True))
        batch_op.add_column(sa.Column('comment_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('size_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prod_size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('leg', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('leg_mtl', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('castor_mtl', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('castor_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stud1_mtl', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stud2_mtl', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('seat_interior_mtl', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('back_interior_mtl', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('scat_interior_mtl', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('material_1_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('material_2_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('material_3_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('material_4_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('material_5_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('material_6_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('material_7_desc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('material_8_desc', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_orders', schema=None) as batch_op:
        batch_op.drop_column('material_8_desc')
        batch_op.drop_column('material_7_desc')
        batch_op.drop_column('material_6_desc')
        batch_op.drop_column('material_5_desc')
        batch_op.drop_column('material_4_desc')
        batch_op.drop_column('material_3_desc')
        batch_op.drop_column('material_2_desc')
        batch_op.drop_column('material_1_desc')
        batch_op.drop_column('scat_interior_mtl')
        batch_op.drop_column('back_interior_mtl')
        batch_op.drop_column('seat_interior_mtl')
        batch_op.drop_column('stud2_mtl')
        batch_op.drop_column('stud1_mtl')
        batch_op.drop_column('castor_desc')
        batch_op.drop_column('castor_mtl')
        batch_op.drop_column('leg_mtl')
        batch_op.drop_column('leg')
        batch_op.drop_column('prod_size')
        batch_op.drop_column('size_desc')
        batch_op.drop_column('comment_text')
        batch_op.drop_column('net_unit_price_gbp')
        batch_op.drop_column('net_unit_price')
        batch_op.drop_column('grn')
        batch_op.drop_column('order_book_comments')
        batch_op.drop_column('ship_to_zip')
        batch_op.drop_column('ship_to_name')
        batch_op.drop_column('order_rel_num')
        batch_op.drop_column('so_type_desc')
        batch_op.drop_column('order_sort')
        batch_op.drop_column('last_xmas_delivery')
        batch_op.drop_column('last_xmas_order_date')
        batch_op.drop_column('order_received_date')
        batch_op.drop_column('customer_delivery_requested')
        batch_op.drop_column('original_need_by')
        batch_op.drop_column('original_ship_by')
        batch_op.drop_column('display_order')
        batch_op.drop_column('guaranteed_christmas')
        batch_op.drop_column('ship_order_complete')
        batch_op.drop_column('customer_credit_hold')
        batch_op.drop_column('so_credit_hold')
        batch_op.drop_column('order_held')
        batch_op.drop_column('firm_line')
        batch_op.drop_column('firm_order')

    # ### end Alembic commands ###
