"""add works_orders table

Revision ID: f97dbf999fe9
Revises: 18359fe21041
Create Date: 2026-07-04 20:22:11.733444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97dbf999fe9'
down_revision = '18359fe21041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_num', sa.String(length=20), nullable=True),
    sa.Column('assembly_seq', sa.Integer(), nullable=True),
    sa.Column('job_released', sa.Boolean(), nullable=True),
    sa.Column('job_firm', sa.Boolean(), nullable=True),
    sa.Column('job_complete', sa.Boolean(), nullable=True),
    sa.Column('req_due_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('load_date', sa.String(length=50), nullable=True),
    sa.Column('req_date', sa.Date(), nullable=True),
    sa.Column('prod_plnwk', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('so_type', sa.String(length=20), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('order_line', sa.Integer(), nullable=True),
    sa.Column('part_num', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('class_id', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('cover', sa.String(length=100), nullable=True),
    sa.Column('cover_type', sa.String(length=100), nullable=True),
    sa.Column('material_1', sa.String(length=50), nullable=True),
    sa.Column('material_2', sa.String(length=50), nullable=True),
    sa.Column('material_3', sa.String(length=50), nullable=True),
    sa.Column('material_4', sa.String(length=50), nullable=True),
    sa.Column('material_5', sa.String(length=50), nullable=True),
    sa.Column('material_6', sa.String(length=50), nullable=True),
    sa.Column('material_7', sa.String(length=50), nullable=True),
    sa.Column('material_8', sa.String(length=50), nullable=True),
    sa.Column('required_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('qty_completed', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('selling_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('shipped_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('next_op', sa.String(length=20), nullable=True),
    sa.Column('wip_warehouse', sa.String(length=20), nullable=True),
    sa.Column('wip_bin', sa.String(length=20), nullable=True),
    sa.Column('waiting_temp', sa.Boolean(), nullable=True),
    sa.Column('mtl_shortage', sa.Boolean(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('works_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_works_orders_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_orders_job_complete'), ['job_complete'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_orders_job_num'), ['job_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_orders_order_num'), ['order_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_orders_part_num'), ['part_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_orders_prod_plnwk'), ['prod_plnwk'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_orders_req_due_date'), ['req_due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_orders_req_due_date'))
        batch_op.drop_index(batch_op.f('ix_works_orders_prod_plnwk'))
        batch_op.drop_index(batch_op.f('ix_works_orders_part_num'))
        batch_op.drop_index(batch_op.f('ix_works_orders_order_num'))
        batch_op.drop_index(batch_op.f('ix_works_orders_job_num'))
        batch_op.drop_index(batch_op.f('ix_works_orders_job_complete'))
        batch_op.drop_index(batch_op.f('ix_works_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_works_orders_class_id'))

    op.drop_table('works_orders')
    # ### end Alembic commands ###
