"""add_customer_group_weekly_capacity

Revision ID: fdb0e49d7fa3
Revises: 1f4d3532887f
Create Date: 2026-08-25 14:02:42.544627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb0e49d7fa3'
down_revision = '1f4d3532887f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_capacity', sa.Numeric(precision=8, scale=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_groups', schema=None) as batch_op:
        batch_op.drop_column('weekly_capacity')

    # ### end Alembic commands ###
